### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by edrdesigner** [webhooksite/webhook.site#103]
Every 10 minutes it deletes all the token url.

Is ther a workarround that?

**Comment by fredsted** [comment]
Try checking if redis is restarting, as the data is stored there and the default docker compose file doesn't have persistence enabled.

**Comment by SnakeA92** [comment]
@fredsted Facing a similar issue - after some time (a few days) I seem to be getting a HTTP 410 - Gone ... and have to regenerate the URL.

Any idea what might be causing this ?

Thanks!
