### ISSUE TITLE
Request headers with characters like "_" or "." not displayed in "headers" section

### ISSUE THREAD

**Issue by ngbalk** [webhooksite/webhook.site#134]
I am using webhook.site to test a GET request which has many headers, but only the headers with characters like "." or "_" are getting ignored by webhook.site.  Is there some header validation that is stripping these out?  Happy to make a PR if someone can point me in the right direction :)

**Comment by fredsted** [comment]
It looks like they may be stripped by Nginx. We have no plans to change this on the cloud version of Webhook.site.
