### ISSUE TITLE
FetchError: request to webhook.site

### ISSUE THREAD

**Issue by sibelius** [webhooksite/webhook.site#140]
webhook api call err:  FetchError: request to https://webhook.site/c6914f1e-999f-43c8-b33c-7e874f979682?authorization=b failed, reason: Socket connection timeout
    at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)

node: 20
node-fetch: 2.6.7

**Comment by fredsted** [comment]
If this happens consistently, please use https://support.webhook.site.
