### ISSUE TITLE
Self Hosted SSL Support?

### ISSUE THREAD

**Issue by gareth-johnstone** [webhooksite/webhook.site#147]
Hi,
I have got webhook.site installed via docker and I have setup an nginx reverse proxy (with nginx reverse proxy manager)

However when i visit the site via https the connection could not be made - any ideas?

**Comment by duckboy81** [comment]
I don't know anything about this project's code, but when you're using `nginx`, you'll need to configure `nginx` to serve the certificate and terminate the ssl connection before passing it to this app.

**Comment by gareth-johnstone** [comment]
> I don't know anything about this project's code, but when you're using `nginx`, you'll need to configure `nginx` to serve the certificate and terminate the ssl connection before passing it to this app.

Sorry this issue should have been closed, I was just being an idiot 😂 Cloudflare was getting in the way (duuhhh)

Thanks for your input anyways, much appreicated :)
