### ISSUE TITLE
docs website unavailable: Unsupported SSL protocol

### ISSUE THREAD

**Issue by agardnerIT** [webhooksite/webhook.site#149]
<img width="383" alt="image" src="https://github.com/webhooksite/webhook.site/assets/26523841/c13c1779-2385-47aa-a40e-b6d1dace4809">

**Comment by fredsted** [comment]
Works fine here in Chrome 116, what's your browser and version?

**Comment by ifgarces** [comment]
The docs website works perfectly on Opera 102.0 too
