### ISSUE TITLE
how can I set the request body for value on webhook.site response body

### ISSUE THREAD

**Issue by arthas3014** [webhooksite/webhook.site#153]
![screenshot-20231123-100748](https://github.com/webhooksite/webhook.site/assets/149747201/06eeb026-9940-4645-ac74-b537e57611da)
how can I set the request body for value on webhook.site response body

**Comment by fredsted** [comment]
Upgrade to Webhook.site Pro, and then use the Extract JSONPath and Modify Response actions. More info here: 

https://docs.webhook.site/custom-actions/action-types.html#extract-jsonpath

https://docs.webhook.site/custom-actions/action-types.html#modify-response
