### ISSUE TITLE
[Feature request] customize email username+hostname

### ISSUE THREAD

**Issue by xiaohuilam** [webhooksite/webhook.site#154]
There are some debug demands to support customize email username and hostname (for example admin@mydomain.com) rather than xxxxxxx-xxxx-xxxx-xxxx-xxxxxx@email.webhook.site.
And if we can support catch-all (for example *@mydomain.com) and it will be awesome!

**Comment by fredsted** [comment]
Hello. If you're a Webhook.site Enterprise customer, we can set this up for you. Please create a ticket on our support portal: https://support.webhook.site
