### ISSUE TITLE
Socket Hang Up on GET token/:id/requests

### ISSUE THREAD

**Issue by awhisler** [webhooksite/webhook.site#167]
I am getting an error sometimes 'socket hang up' on GET token/:id/requests
Here is my method:
```
static async getWebhookRequest({ request, page }, id: string, length = 1) {
        const maxRetries = 40;
        let response;
        for (let i = 0; i < maxRetries; i++) {
            response = await request.get(`https://webhook.site/token/${id}/requests?query=method:POST`, {
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                }
            });
            if (response.status() !== 200) {
                console.error(`Error getting webhook id '${id}'`, await response.status(), await response.json());
                return;
            }
            await page.goto(`https://webhook.site/${id}`);
            const json = await response.json();
            if ((await json.data).length >= length) {
                return await response.json();
            }
        }
```
I read that some causes of this is due to not having the correct headers. According to [this](https://docs.webhook.site/api/about.html) I should have content-type and accept be `application/json` so I did but I still get the issue

**Comment by fredsted** [comment]
It seems like you're spamming the API 40 times in a row. Please don't abuse the API like that, at least add a setTimeout. (Example here: https://docs.webhook.site/api/examples.html#download-all-request-data-as-files_2)

I can't comment on the error you're getting as you didn't include any timestamps or indication of frequency. Network errors happen.

**Comment by awhisler** [comment]
@fredsted I am "spamming" the API because it isn't returning my requests in a timely manner. I ran 1300 tests every night and no other test gives a network error besides this one and it is complaining about this call.

This ran at 3AM MST today
![image](https://github.com/user-attachments/assets/ef036702-1805-4ae9-9545-aef19c1ea71e)

**Comment by fredsted** [comment]
Are you a paid customer of Webhook.site?

**Comment by awhisler** [comment]
I am not

**Comment by fredsted** [comment]
Please stop abusing the API like this, or create a subscription so I can cover the resources you're using.
