### ISSUE TITLE
How to setup self-hosted at least like webhook.site website? 

### ISSUE THREAD

**Issue by che0one** [webhooksite/webhook.site#170]
Recently deployed webhook.site docker image and that looks so weird compared to free webhook.site website, can anyone explain is there a way to setup dns and smtp settings or 🗑️?
Guys please share screenshot of self-hosted 🗑️ version don't waste our time... That is definetely only bin part of requestbin

**Comment by fredsted** [comment]
See here: https://docs.webhook.site/open-source.html
