### ISSUE TITLE
Increase 500 request limit for webhooks

### ISSUE THREAD

**Issue by wdhdev** [webhooksite/webhook.site#171]
I am using a self hosted version of webhook.site, and am running into the issue of `This URL received over 500 requests and can't accept more webhooks.`

Is there a way to either increase or remove this limit completely, such as an environmental variable or such?

I'm using Docker compose.

**Comment by fredsted** [comment]
You can change this limit using the environment variable `WEBHOOK_MAX_REQUESTS`.
