### ISSUE TITLE
I am newbie.How to get the message from my computer after new message at webhook.site?

### ISSUE THREAD

**Issue by david03kimo** [webhooksite/webhook.site#97]
I set tradingview alerts too webhook.site,it works perfect.
I'd like to know can webhook send the message to my python program after it received new message?

thanks.

**Comment by mavaddat** [comment]
The purpose of [GitHub Issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues) is to notify the developers of problems with their product or project. It looks like you're seeking advice for how to implement a solution that uses webhook.site. That's not typically [what GitHub issues is intended to address](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde).
You might want to try posting your question on a site like [Stackoverflow](https://stackoverflow.com/questions/tagged/webhooks), [Quora](https://python-programming.quora.com/) or [Reddit r/LearnProgramming](https://www.reddit.com/r/learnprogramming).
